name: podsonly
description: A podcast listener app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  podcast_search: ^0.6.1
  dio: ^5.2.1+1
  rich_readmore: ^1.0.5
  intl: ^0.18.1
  just_audio: ^0.9.34
  html: ^0.15.4
  just_audio_background: ^0.0.1-beta.10
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
